version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        BOT_NAME: "${BOT_NAME}"
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - db_data:/usr/src/app/${BOT_NAME}/data
    command: python3 __main__.py
    restart: always
    environment:
      - BOT_NAME=${BOT_NAME}
    env_file:
      - ".env"
    networks:
      - tg_bot
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --port $REDIS__PORT --save 20 1 --loglevel warning
    env_file:
      - ".env"
    volumes:
      - cache:/data
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge

volumes:
  cache:
  db_data: