import { Unit } from "./types";

export const units: Unit[] = [
    {
      id: "unit7",
      name: "Unit 7: Software. Types of software",
      words: {
        "application software": "прикладне програмне забезпечення",
        "back-up": "резервне копіювання",
        bug: "помилка спричинена програмістом",
        calculation: "обчислення",
        "closed source": "із закритим кодом",
        compatible: "сумісний",
        database: "база данних",
        "desktop publishing": "комп'ютерна верстка",
        embedded: "вбудований",
        "end user": "кінцевий користувач",
        error: "помилка спричинена неуважністю",
        feature: "особливість, функція",
        firmware: "вбудоване програмне забезпечення, прошивка",
        flowchart: "блок-схема",
        "IDE (integrated development environment)": "інтегроване середовище розробки",
        kernel: "ядро",
        manually: "вручну",
        "open source software": "програмне забезпечення з відкритим кодом",
        "paging file (page file)": "файл підкачки",
        "proprietary software": "власницьке (пропрієтарне) програмне забезпечення",
        restriction: "обмеження",
        sequence: "послідовність",
        "source code": "вихідний код",
        spreadsheet: "електронна таблиця",
        "system software": "системне програмне забезпечення",
        "task manager": "диспетчер завдань",
        "to abort": "перервати",
        "to compile": "компілювати, упорядковувати",
        "to debug": "відлагоджувати",
        "to edit": "редагувати",
        "to fix": "виправити, відремонтувати",
        "to restore": "відновлювати",
        "to terminate, to restrict": "обмежувати",
        usability: "зручність у користуванні",
        "wide range": "широкий спектр",
        "word processing": "текстова обробка",
        "word processor": "текстовий редактор"
      },
    },
    {
      id: "unit8",
      name: "Unit 8: Operating systems. Graphical user interface",
      words: {
        allocates: "виділяти",
        "assembly language": "мова асемблера",
        background: "фон",
        button: "кнопка, клавіша",
        "check box": "позначка, прапорець",
        "consumer electronics": "споживча електроніка",
        desktop: "робочий стіл",
        "drop-down menu": "випадне меню",
        folder: "папка",
        "handwriting recognition": "розпізнавання рукописного тексту",
        "high-level language": "високорівнева мова",
        impact: "вплив",
        interaction: "взаємодія",
        kernel: "ядро",
        pointer: "вказівник",
        portability: "портативність",
        "recycle bin, wastebasket": "корзина",
        scrollbar: "панель прокрутки",
        shell: "оболонка",
        "speech recognition": "розпізнавання мовлення",
        submenu: "підменю",
        taskbar: "панель завдань",
        "to benefit": "отримати перевагу",
        "to broaden": "розширювати",
        "to check": "позначати; перевірити",
        "to improve": "покращувати",
        "to interact": "взаємодіяти",
        "to involve": "включати, залучати",
        "to uncheck": "зняти позначку"
      },
    },
    {
      id: "unit9",
      name: "Unit 9: Ergonomics. A good workspace. Health and safety",
      words: {
        "ache, pain": "біль",
        angle: "кут, розташовувати під кутом",
        copyholder: "підставка під папери",
        edge: "край",
        excessive: "надлишковий",
        frequent: "частий",
        glare: "блиск",
        pad: "коврик",
        posture: "постава",
        pressure: "тиск",
        reflection: "відображення",
        shortcut: "ярлик",
        strain: "напруга, напруження",
        tilt: "нахил, нахиляти",
        "to adjust": "регулювати",
        "to alternate": "змінити, замінити",
        "to avoid": "уникати",
        "to bend": "нагинати, вигинати",
        "to counteract": "протидіяти",
        "to eliminate": "усунути",
        "to key, to type": "друкувати, вводити (інформацію в комп'ютер)",
        "to position": "розташовувати",
        "to recline": "відхилити",
        "to reduce": "зменшити, скоротити",
        "to support, to sustain": "підтримувати, сприяти",
        "to twist": "підвернути, викрутити",
        "to utilize": "використовувати",
        vital: "важливий",
        wrist: "зап'ясток",
        customize: "налаштувати"
      }
    },
  ];