name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend/casino-app
          npm install

      - name: Build project
        run: |
          cd frontend/casino-app
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: frontend/casino-app/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: frontend/casino-app/dist/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: scp -r frontend/casino-app/dist/* ${{ secrets.DEPLOY_USER }}
