name: Build and Deploy Casino and Wordle Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies and build casino-app
        run: |
          cd frontend/casino-app
          npm install
          npm run build

      - name: Upload casino-app build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: casino-app-build
          path: frontend/casino-app/dist/

      - name: Install dependencies and build wordle-app
        run: |
          cd frontend/wordle-app
          npm install
          npm run build

      - name: Upload wordle-app build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wordle-app-build
          path: frontend/wordle-app/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download casino-app build artifacts
        uses: actions/download-artifact@v2
        with:
          name: casino-app-build
          path: dist/casino-app/dist

      - name: Download wordle-app build artifacts
        uses: actions/download-artifact@v2
        with:
          name: wordle-app-build
          path: dist/wordle-app/dist

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp -r dist/casino-app/dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.DEPLOY_PATH }}/casino-app
          scp -r dist/wordle-app/dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.DEPLOY_PATH }}/wordle-app
